//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConUniServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaAutenticacion", Namespace="http://schemas.datacontract.org/2004/07/ConUni_Soap_Dotnet_GR06.Modelos")]
    public partial class RespuestaAutenticacion : object
    {
        
        private bool ExitosoField;
        
        private string MensajeField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Exitoso
        {
            get
            {
                return this.ExitosoField;
            }
            set
            {
                this.ExitosoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConUniServiceReference.IConversorUnidadesWS")]
    public interface IConversorUnidadesWS
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversorUnidadesWS/Login", ReplyAction="http://tempuri.org/IConversorUnidadesWS/LoginResponse")]
        ConUniServiceReference.RespuestaAutenticacion Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversorUnidadesWS/CelsiusAFahrenheit", ReplyAction="http://tempuri.org/IConversorUnidadesWS/CelsiusAFahrenheitResponse")]
        double CelsiusAFahrenheit(double celsius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversorUnidadesWS/FahrenheitACelsius", ReplyAction="http://tempuri.org/IConversorUnidadesWS/FahrenheitACelsiusResponse")]
        double FahrenheitACelsius(double fahrenheit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversorUnidadesWS/CelsiusAKelvin", ReplyAction="http://tempuri.org/IConversorUnidadesWS/CelsiusAKelvinResponse")]
        double CelsiusAKelvin(double celsius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversorUnidadesWS/KelvinACelsius", ReplyAction="http://tempuri.org/IConversorUnidadesWS/KelvinACelsiusResponse")]
        double KelvinACelsius(double kelvin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversorUnidadesWS/FahrenheitAKelvin", ReplyAction="http://tempuri.org/IConversorUnidadesWS/FahrenheitAKelvinResponse")]
        double FahrenheitAKelvin(double fahrenheit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversorUnidadesWS/KelvinAFahrenheit", ReplyAction="http://tempuri.org/IConversorUnidadesWS/KelvinAFahrenheitResponse")]
        double KelvinAFahrenheit(double kelvin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversorUnidadesWS/MetroAKilometro", ReplyAction="http://tempuri.org/IConversorUnidadesWS/MetroAKilometroResponse")]
        double MetroAKilometro(double metros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversorUnidadesWS/KilometroAMetro", ReplyAction="http://tempuri.org/IConversorUnidadesWS/KilometroAMetroResponse")]
        double KilometroAMetro(double kilometros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversorUnidadesWS/MetroAMilla", ReplyAction="http://tempuri.org/IConversorUnidadesWS/MetroAMillaResponse")]
        double MetroAMilla(double metros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversorUnidadesWS/MillaAMetro", ReplyAction="http://tempuri.org/IConversorUnidadesWS/MillaAMetroResponse")]
        double MillaAMetro(double millas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversorUnidadesWS/KilometroAMilla", ReplyAction="http://tempuri.org/IConversorUnidadesWS/KilometroAMillaResponse")]
        double KilometroAMilla(double kilometros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversorUnidadesWS/MillaAKilometro", ReplyAction="http://tempuri.org/IConversorUnidadesWS/MillaAKilometroResponse")]
        double MillaAKilometro(double millas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversorUnidadesWS/KilogramoAGramo", ReplyAction="http://tempuri.org/IConversorUnidadesWS/KilogramoAGramoResponse")]
        double KilogramoAGramo(double kilogramos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversorUnidadesWS/GramoAKilogramo", ReplyAction="http://tempuri.org/IConversorUnidadesWS/GramoAKilogramoResponse")]
        double GramoAKilogramo(double gramos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversorUnidadesWS/KilogramoALibra", ReplyAction="http://tempuri.org/IConversorUnidadesWS/KilogramoALibraResponse")]
        double KilogramoALibra(double kilogramos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversorUnidadesWS/LibraAKilogramo", ReplyAction="http://tempuri.org/IConversorUnidadesWS/LibraAKilogramoResponse")]
        double LibraAKilogramo(double libras);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversorUnidadesWS/GramoALibra", ReplyAction="http://tempuri.org/IConversorUnidadesWS/GramoALibraResponse")]
        double GramoALibra(double gramos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversorUnidadesWS/LibraAGramo", ReplyAction="http://tempuri.org/IConversorUnidadesWS/LibraAGramoResponse")]
        double LibraAGramo(double libras);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IConversorUnidadesWSChannel : ConUniServiceReference.IConversorUnidadesWS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ConversorUnidadesWSClient : System.ServiceModel.ClientBase<ConUniServiceReference.IConversorUnidadesWS>, ConUniServiceReference.IConversorUnidadesWS
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ConversorUnidadesWSClient() : 
                base(ConversorUnidadesWSClient.GetDefaultBinding(), ConversorUnidadesWSClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IConversorUnidadesWS.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConversorUnidadesWSClient(EndpointConfiguration endpointConfiguration) : 
                base(ConversorUnidadesWSClient.GetBindingForEndpoint(endpointConfiguration), ConversorUnidadesWSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConversorUnidadesWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ConversorUnidadesWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConversorUnidadesWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ConversorUnidadesWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConversorUnidadesWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ConUniServiceReference.RespuestaAutenticacion Login(string username, string password)
        {
            return base.Channel.Login(username, password);
        }
        
        public double CelsiusAFahrenheit(double celsius)
        {
            return base.Channel.CelsiusAFahrenheit(celsius);
        }
        
        public double FahrenheitACelsius(double fahrenheit)
        {
            return base.Channel.FahrenheitACelsius(fahrenheit);
        }
        
        public double CelsiusAKelvin(double celsius)
        {
            return base.Channel.CelsiusAKelvin(celsius);
        }
        
        public double KelvinACelsius(double kelvin)
        {
            return base.Channel.KelvinACelsius(kelvin);
        }
        
        public double FahrenheitAKelvin(double fahrenheit)
        {
            return base.Channel.FahrenheitAKelvin(fahrenheit);
        }
        
        public double KelvinAFahrenheit(double kelvin)
        {
            return base.Channel.KelvinAFahrenheit(kelvin);
        }
        
        public double MetroAKilometro(double metros)
        {
            return base.Channel.MetroAKilometro(metros);
        }
        
        public double KilometroAMetro(double kilometros)
        {
            return base.Channel.KilometroAMetro(kilometros);
        }
        
        public double MetroAMilla(double metros)
        {
            return base.Channel.MetroAMilla(metros);
        }
        
        public double MillaAMetro(double millas)
        {
            return base.Channel.MillaAMetro(millas);
        }
        
        public double KilometroAMilla(double kilometros)
        {
            return base.Channel.KilometroAMilla(kilometros);
        }
        
        public double MillaAKilometro(double millas)
        {
            return base.Channel.MillaAKilometro(millas);
        }
        
        public double KilogramoAGramo(double kilogramos)
        {
            return base.Channel.KilogramoAGramo(kilogramos);
        }
        
        public double GramoAKilogramo(double gramos)
        {
            return base.Channel.GramoAKilogramo(gramos);
        }
        
        public double KilogramoALibra(double kilogramos)
        {
            return base.Channel.KilogramoALibra(kilogramos);
        }
        
        public double LibraAKilogramo(double libras)
        {
            return base.Channel.LibraAKilogramo(libras);
        }
        
        public double GramoALibra(double gramos)
        {
            return base.Channel.GramoALibra(gramos);
        }
        
        public double LibraAGramo(double libras)
        {
            return base.Channel.LibraAGramo(libras);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IConversorUnidadesWS))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IConversorUnidadesWS))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:61088/WebServices/ConversorUnidadesWS.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ConversorUnidadesWSClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IConversorUnidadesWS);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ConversorUnidadesWSClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IConversorUnidadesWS);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IConversorUnidadesWS,
        }
    }
}
