//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ConUni_Client_Escritorio_DotNet.localhost {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IConversorUnidadesWS", Namespace="http://tempuri.org/")]
    public partial class ConversorUnidadesWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback CelsiusAFahrenheitOperationCompleted;
        
        private System.Threading.SendOrPostCallback FahrenheitACelsiusOperationCompleted;
        
        private System.Threading.SendOrPostCallback CelsiusAKelvinOperationCompleted;
        
        private System.Threading.SendOrPostCallback KelvinACelsiusOperationCompleted;
        
        private System.Threading.SendOrPostCallback FahrenheitAKelvinOperationCompleted;
        
        private System.Threading.SendOrPostCallback KelvinAFahrenheitOperationCompleted;
        
        private System.Threading.SendOrPostCallback MetroAKilometroOperationCompleted;
        
        private System.Threading.SendOrPostCallback KilometroAMetroOperationCompleted;
        
        private System.Threading.SendOrPostCallback MetroAMillaOperationCompleted;
        
        private System.Threading.SendOrPostCallback MillaAMetroOperationCompleted;
        
        private System.Threading.SendOrPostCallback KilometroAMillaOperationCompleted;
        
        private System.Threading.SendOrPostCallback MillaAKilometroOperationCompleted;
        
        private System.Threading.SendOrPostCallback KilogramoAGramoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GramoAKilogramoOperationCompleted;
        
        private System.Threading.SendOrPostCallback KilogramoALibraOperationCompleted;
        
        private System.Threading.SendOrPostCallback LibraAKilogramoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GramoALibraOperationCompleted;
        
        private System.Threading.SendOrPostCallback LibraAGramoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ConversorUnidadesWS() {
            this.Url = global::ConUni_Client_Escritorio_DotNet.Properties.Settings.Default.ConUni_Client_Escritorio_DotNet_localhost_ConversorUnidadesWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event CelsiusAFahrenheitCompletedEventHandler CelsiusAFahrenheitCompleted;
        
        /// <remarks/>
        public event FahrenheitACelsiusCompletedEventHandler FahrenheitACelsiusCompleted;
        
        /// <remarks/>
        public event CelsiusAKelvinCompletedEventHandler CelsiusAKelvinCompleted;
        
        /// <remarks/>
        public event KelvinACelsiusCompletedEventHandler KelvinACelsiusCompleted;
        
        /// <remarks/>
        public event FahrenheitAKelvinCompletedEventHandler FahrenheitAKelvinCompleted;
        
        /// <remarks/>
        public event KelvinAFahrenheitCompletedEventHandler KelvinAFahrenheitCompleted;
        
        /// <remarks/>
        public event MetroAKilometroCompletedEventHandler MetroAKilometroCompleted;
        
        /// <remarks/>
        public event KilometroAMetroCompletedEventHandler KilometroAMetroCompleted;
        
        /// <remarks/>
        public event MetroAMillaCompletedEventHandler MetroAMillaCompleted;
        
        /// <remarks/>
        public event MillaAMetroCompletedEventHandler MillaAMetroCompleted;
        
        /// <remarks/>
        public event KilometroAMillaCompletedEventHandler KilometroAMillaCompleted;
        
        /// <remarks/>
        public event MillaAKilometroCompletedEventHandler MillaAKilometroCompleted;
        
        /// <remarks/>
        public event KilogramoAGramoCompletedEventHandler KilogramoAGramoCompleted;
        
        /// <remarks/>
        public event GramoAKilogramoCompletedEventHandler GramoAKilogramoCompleted;
        
        /// <remarks/>
        public event KilogramoALibraCompletedEventHandler KilogramoALibraCompleted;
        
        /// <remarks/>
        public event LibraAKilogramoCompletedEventHandler LibraAKilogramoCompleted;
        
        /// <remarks/>
        public event GramoALibraCompletedEventHandler GramoALibraCompleted;
        
        /// <remarks/>
        public event LibraAGramoCompletedEventHandler LibraAGramoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IConversorUnidadesWS/Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RespuestaAutenticacion Login([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string username, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password) {
            object[] results = this.Invoke("Login", new object[] {
                        username,
                        password});
            return ((RespuestaAutenticacion)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string username, string password) {
            this.LoginAsync(username, password, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string username, string password, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        username,
                        password}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IConversorUnidadesWS/CelsiusAFahrenheit", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CelsiusAFahrenheit(double celsius, [System.Xml.Serialization.XmlIgnoreAttribute()] bool celsiusSpecified, out double CelsiusAFahrenheitResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool CelsiusAFahrenheitResultSpecified) {
            object[] results = this.Invoke("CelsiusAFahrenheit", new object[] {
                        celsius,
                        celsiusSpecified});
            CelsiusAFahrenheitResult = ((double)(results[0]));
            CelsiusAFahrenheitResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void CelsiusAFahrenheitAsync(double celsius, bool celsiusSpecified) {
            this.CelsiusAFahrenheitAsync(celsius, celsiusSpecified, null);
        }
        
        /// <remarks/>
        public void CelsiusAFahrenheitAsync(double celsius, bool celsiusSpecified, object userState) {
            if ((this.CelsiusAFahrenheitOperationCompleted == null)) {
                this.CelsiusAFahrenheitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCelsiusAFahrenheitOperationCompleted);
            }
            this.InvokeAsync("CelsiusAFahrenheit", new object[] {
                        celsius,
                        celsiusSpecified}, this.CelsiusAFahrenheitOperationCompleted, userState);
        }
        
        private void OnCelsiusAFahrenheitOperationCompleted(object arg) {
            if ((this.CelsiusAFahrenheitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CelsiusAFahrenheitCompleted(this, new CelsiusAFahrenheitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IConversorUnidadesWS/FahrenheitACelsius", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void FahrenheitACelsius(double fahrenheit, [System.Xml.Serialization.XmlIgnoreAttribute()] bool fahrenheitSpecified, out double FahrenheitACelsiusResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool FahrenheitACelsiusResultSpecified) {
            object[] results = this.Invoke("FahrenheitACelsius", new object[] {
                        fahrenheit,
                        fahrenheitSpecified});
            FahrenheitACelsiusResult = ((double)(results[0]));
            FahrenheitACelsiusResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void FahrenheitACelsiusAsync(double fahrenheit, bool fahrenheitSpecified) {
            this.FahrenheitACelsiusAsync(fahrenheit, fahrenheitSpecified, null);
        }
        
        /// <remarks/>
        public void FahrenheitACelsiusAsync(double fahrenheit, bool fahrenheitSpecified, object userState) {
            if ((this.FahrenheitACelsiusOperationCompleted == null)) {
                this.FahrenheitACelsiusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFahrenheitACelsiusOperationCompleted);
            }
            this.InvokeAsync("FahrenheitACelsius", new object[] {
                        fahrenheit,
                        fahrenheitSpecified}, this.FahrenheitACelsiusOperationCompleted, userState);
        }
        
        private void OnFahrenheitACelsiusOperationCompleted(object arg) {
            if ((this.FahrenheitACelsiusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FahrenheitACelsiusCompleted(this, new FahrenheitACelsiusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IConversorUnidadesWS/CelsiusAKelvin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CelsiusAKelvin(double celsius, [System.Xml.Serialization.XmlIgnoreAttribute()] bool celsiusSpecified, out double CelsiusAKelvinResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool CelsiusAKelvinResultSpecified) {
            object[] results = this.Invoke("CelsiusAKelvin", new object[] {
                        celsius,
                        celsiusSpecified});
            CelsiusAKelvinResult = ((double)(results[0]));
            CelsiusAKelvinResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void CelsiusAKelvinAsync(double celsius, bool celsiusSpecified) {
            this.CelsiusAKelvinAsync(celsius, celsiusSpecified, null);
        }
        
        /// <remarks/>
        public void CelsiusAKelvinAsync(double celsius, bool celsiusSpecified, object userState) {
            if ((this.CelsiusAKelvinOperationCompleted == null)) {
                this.CelsiusAKelvinOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCelsiusAKelvinOperationCompleted);
            }
            this.InvokeAsync("CelsiusAKelvin", new object[] {
                        celsius,
                        celsiusSpecified}, this.CelsiusAKelvinOperationCompleted, userState);
        }
        
        private void OnCelsiusAKelvinOperationCompleted(object arg) {
            if ((this.CelsiusAKelvinCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CelsiusAKelvinCompleted(this, new CelsiusAKelvinCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IConversorUnidadesWS/KelvinACelsius", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void KelvinACelsius(double kelvin, [System.Xml.Serialization.XmlIgnoreAttribute()] bool kelvinSpecified, out double KelvinACelsiusResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool KelvinACelsiusResultSpecified) {
            object[] results = this.Invoke("KelvinACelsius", new object[] {
                        kelvin,
                        kelvinSpecified});
            KelvinACelsiusResult = ((double)(results[0]));
            KelvinACelsiusResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void KelvinACelsiusAsync(double kelvin, bool kelvinSpecified) {
            this.KelvinACelsiusAsync(kelvin, kelvinSpecified, null);
        }
        
        /// <remarks/>
        public void KelvinACelsiusAsync(double kelvin, bool kelvinSpecified, object userState) {
            if ((this.KelvinACelsiusOperationCompleted == null)) {
                this.KelvinACelsiusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKelvinACelsiusOperationCompleted);
            }
            this.InvokeAsync("KelvinACelsius", new object[] {
                        kelvin,
                        kelvinSpecified}, this.KelvinACelsiusOperationCompleted, userState);
        }
        
        private void OnKelvinACelsiusOperationCompleted(object arg) {
            if ((this.KelvinACelsiusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KelvinACelsiusCompleted(this, new KelvinACelsiusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IConversorUnidadesWS/FahrenheitAKelvin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void FahrenheitAKelvin(double fahrenheit, [System.Xml.Serialization.XmlIgnoreAttribute()] bool fahrenheitSpecified, out double FahrenheitAKelvinResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool FahrenheitAKelvinResultSpecified) {
            object[] results = this.Invoke("FahrenheitAKelvin", new object[] {
                        fahrenheit,
                        fahrenheitSpecified});
            FahrenheitAKelvinResult = ((double)(results[0]));
            FahrenheitAKelvinResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void FahrenheitAKelvinAsync(double fahrenheit, bool fahrenheitSpecified) {
            this.FahrenheitAKelvinAsync(fahrenheit, fahrenheitSpecified, null);
        }
        
        /// <remarks/>
        public void FahrenheitAKelvinAsync(double fahrenheit, bool fahrenheitSpecified, object userState) {
            if ((this.FahrenheitAKelvinOperationCompleted == null)) {
                this.FahrenheitAKelvinOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFahrenheitAKelvinOperationCompleted);
            }
            this.InvokeAsync("FahrenheitAKelvin", new object[] {
                        fahrenheit,
                        fahrenheitSpecified}, this.FahrenheitAKelvinOperationCompleted, userState);
        }
        
        private void OnFahrenheitAKelvinOperationCompleted(object arg) {
            if ((this.FahrenheitAKelvinCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FahrenheitAKelvinCompleted(this, new FahrenheitAKelvinCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IConversorUnidadesWS/KelvinAFahrenheit", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void KelvinAFahrenheit(double kelvin, [System.Xml.Serialization.XmlIgnoreAttribute()] bool kelvinSpecified, out double KelvinAFahrenheitResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool KelvinAFahrenheitResultSpecified) {
            object[] results = this.Invoke("KelvinAFahrenheit", new object[] {
                        kelvin,
                        kelvinSpecified});
            KelvinAFahrenheitResult = ((double)(results[0]));
            KelvinAFahrenheitResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void KelvinAFahrenheitAsync(double kelvin, bool kelvinSpecified) {
            this.KelvinAFahrenheitAsync(kelvin, kelvinSpecified, null);
        }
        
        /// <remarks/>
        public void KelvinAFahrenheitAsync(double kelvin, bool kelvinSpecified, object userState) {
            if ((this.KelvinAFahrenheitOperationCompleted == null)) {
                this.KelvinAFahrenheitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKelvinAFahrenheitOperationCompleted);
            }
            this.InvokeAsync("KelvinAFahrenheit", new object[] {
                        kelvin,
                        kelvinSpecified}, this.KelvinAFahrenheitOperationCompleted, userState);
        }
        
        private void OnKelvinAFahrenheitOperationCompleted(object arg) {
            if ((this.KelvinAFahrenheitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KelvinAFahrenheitCompleted(this, new KelvinAFahrenheitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IConversorUnidadesWS/MetroAKilometro", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void MetroAKilometro(double metros, [System.Xml.Serialization.XmlIgnoreAttribute()] bool metrosSpecified, out double MetroAKilometroResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool MetroAKilometroResultSpecified) {
            object[] results = this.Invoke("MetroAKilometro", new object[] {
                        metros,
                        metrosSpecified});
            MetroAKilometroResult = ((double)(results[0]));
            MetroAKilometroResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void MetroAKilometroAsync(double metros, bool metrosSpecified) {
            this.MetroAKilometroAsync(metros, metrosSpecified, null);
        }
        
        /// <remarks/>
        public void MetroAKilometroAsync(double metros, bool metrosSpecified, object userState) {
            if ((this.MetroAKilometroOperationCompleted == null)) {
                this.MetroAKilometroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMetroAKilometroOperationCompleted);
            }
            this.InvokeAsync("MetroAKilometro", new object[] {
                        metros,
                        metrosSpecified}, this.MetroAKilometroOperationCompleted, userState);
        }
        
        private void OnMetroAKilometroOperationCompleted(object arg) {
            if ((this.MetroAKilometroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MetroAKilometroCompleted(this, new MetroAKilometroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IConversorUnidadesWS/KilometroAMetro", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void KilometroAMetro(double kilometros, [System.Xml.Serialization.XmlIgnoreAttribute()] bool kilometrosSpecified, out double KilometroAMetroResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool KilometroAMetroResultSpecified) {
            object[] results = this.Invoke("KilometroAMetro", new object[] {
                        kilometros,
                        kilometrosSpecified});
            KilometroAMetroResult = ((double)(results[0]));
            KilometroAMetroResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void KilometroAMetroAsync(double kilometros, bool kilometrosSpecified) {
            this.KilometroAMetroAsync(kilometros, kilometrosSpecified, null);
        }
        
        /// <remarks/>
        public void KilometroAMetroAsync(double kilometros, bool kilometrosSpecified, object userState) {
            if ((this.KilometroAMetroOperationCompleted == null)) {
                this.KilometroAMetroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKilometroAMetroOperationCompleted);
            }
            this.InvokeAsync("KilometroAMetro", new object[] {
                        kilometros,
                        kilometrosSpecified}, this.KilometroAMetroOperationCompleted, userState);
        }
        
        private void OnKilometroAMetroOperationCompleted(object arg) {
            if ((this.KilometroAMetroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KilometroAMetroCompleted(this, new KilometroAMetroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IConversorUnidadesWS/MetroAMilla", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void MetroAMilla(double metros, [System.Xml.Serialization.XmlIgnoreAttribute()] bool metrosSpecified, out double MetroAMillaResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool MetroAMillaResultSpecified) {
            object[] results = this.Invoke("MetroAMilla", new object[] {
                        metros,
                        metrosSpecified});
            MetroAMillaResult = ((double)(results[0]));
            MetroAMillaResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void MetroAMillaAsync(double metros, bool metrosSpecified) {
            this.MetroAMillaAsync(metros, metrosSpecified, null);
        }
        
        /// <remarks/>
        public void MetroAMillaAsync(double metros, bool metrosSpecified, object userState) {
            if ((this.MetroAMillaOperationCompleted == null)) {
                this.MetroAMillaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMetroAMillaOperationCompleted);
            }
            this.InvokeAsync("MetroAMilla", new object[] {
                        metros,
                        metrosSpecified}, this.MetroAMillaOperationCompleted, userState);
        }
        
        private void OnMetroAMillaOperationCompleted(object arg) {
            if ((this.MetroAMillaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MetroAMillaCompleted(this, new MetroAMillaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IConversorUnidadesWS/MillaAMetro", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void MillaAMetro(double millas, [System.Xml.Serialization.XmlIgnoreAttribute()] bool millasSpecified, out double MillaAMetroResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool MillaAMetroResultSpecified) {
            object[] results = this.Invoke("MillaAMetro", new object[] {
                        millas,
                        millasSpecified});
            MillaAMetroResult = ((double)(results[0]));
            MillaAMetroResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void MillaAMetroAsync(double millas, bool millasSpecified) {
            this.MillaAMetroAsync(millas, millasSpecified, null);
        }
        
        /// <remarks/>
        public void MillaAMetroAsync(double millas, bool millasSpecified, object userState) {
            if ((this.MillaAMetroOperationCompleted == null)) {
                this.MillaAMetroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMillaAMetroOperationCompleted);
            }
            this.InvokeAsync("MillaAMetro", new object[] {
                        millas,
                        millasSpecified}, this.MillaAMetroOperationCompleted, userState);
        }
        
        private void OnMillaAMetroOperationCompleted(object arg) {
            if ((this.MillaAMetroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MillaAMetroCompleted(this, new MillaAMetroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IConversorUnidadesWS/KilometroAMilla", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void KilometroAMilla(double kilometros, [System.Xml.Serialization.XmlIgnoreAttribute()] bool kilometrosSpecified, out double KilometroAMillaResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool KilometroAMillaResultSpecified) {
            object[] results = this.Invoke("KilometroAMilla", new object[] {
                        kilometros,
                        kilometrosSpecified});
            KilometroAMillaResult = ((double)(results[0]));
            KilometroAMillaResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void KilometroAMillaAsync(double kilometros, bool kilometrosSpecified) {
            this.KilometroAMillaAsync(kilometros, kilometrosSpecified, null);
        }
        
        /// <remarks/>
        public void KilometroAMillaAsync(double kilometros, bool kilometrosSpecified, object userState) {
            if ((this.KilometroAMillaOperationCompleted == null)) {
                this.KilometroAMillaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKilometroAMillaOperationCompleted);
            }
            this.InvokeAsync("KilometroAMilla", new object[] {
                        kilometros,
                        kilometrosSpecified}, this.KilometroAMillaOperationCompleted, userState);
        }
        
        private void OnKilometroAMillaOperationCompleted(object arg) {
            if ((this.KilometroAMillaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KilometroAMillaCompleted(this, new KilometroAMillaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IConversorUnidadesWS/MillaAKilometro", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void MillaAKilometro(double millas, [System.Xml.Serialization.XmlIgnoreAttribute()] bool millasSpecified, out double MillaAKilometroResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool MillaAKilometroResultSpecified) {
            object[] results = this.Invoke("MillaAKilometro", new object[] {
                        millas,
                        millasSpecified});
            MillaAKilometroResult = ((double)(results[0]));
            MillaAKilometroResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void MillaAKilometroAsync(double millas, bool millasSpecified) {
            this.MillaAKilometroAsync(millas, millasSpecified, null);
        }
        
        /// <remarks/>
        public void MillaAKilometroAsync(double millas, bool millasSpecified, object userState) {
            if ((this.MillaAKilometroOperationCompleted == null)) {
                this.MillaAKilometroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMillaAKilometroOperationCompleted);
            }
            this.InvokeAsync("MillaAKilometro", new object[] {
                        millas,
                        millasSpecified}, this.MillaAKilometroOperationCompleted, userState);
        }
        
        private void OnMillaAKilometroOperationCompleted(object arg) {
            if ((this.MillaAKilometroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MillaAKilometroCompleted(this, new MillaAKilometroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IConversorUnidadesWS/KilogramoAGramo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void KilogramoAGramo(double kilogramos, [System.Xml.Serialization.XmlIgnoreAttribute()] bool kilogramosSpecified, out double KilogramoAGramoResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool KilogramoAGramoResultSpecified) {
            object[] results = this.Invoke("KilogramoAGramo", new object[] {
                        kilogramos,
                        kilogramosSpecified});
            KilogramoAGramoResult = ((double)(results[0]));
            KilogramoAGramoResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void KilogramoAGramoAsync(double kilogramos, bool kilogramosSpecified) {
            this.KilogramoAGramoAsync(kilogramos, kilogramosSpecified, null);
        }
        
        /// <remarks/>
        public void KilogramoAGramoAsync(double kilogramos, bool kilogramosSpecified, object userState) {
            if ((this.KilogramoAGramoOperationCompleted == null)) {
                this.KilogramoAGramoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKilogramoAGramoOperationCompleted);
            }
            this.InvokeAsync("KilogramoAGramo", new object[] {
                        kilogramos,
                        kilogramosSpecified}, this.KilogramoAGramoOperationCompleted, userState);
        }
        
        private void OnKilogramoAGramoOperationCompleted(object arg) {
            if ((this.KilogramoAGramoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KilogramoAGramoCompleted(this, new KilogramoAGramoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IConversorUnidadesWS/GramoAKilogramo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GramoAKilogramo(double gramos, [System.Xml.Serialization.XmlIgnoreAttribute()] bool gramosSpecified, out double GramoAKilogramoResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool GramoAKilogramoResultSpecified) {
            object[] results = this.Invoke("GramoAKilogramo", new object[] {
                        gramos,
                        gramosSpecified});
            GramoAKilogramoResult = ((double)(results[0]));
            GramoAKilogramoResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void GramoAKilogramoAsync(double gramos, bool gramosSpecified) {
            this.GramoAKilogramoAsync(gramos, gramosSpecified, null);
        }
        
        /// <remarks/>
        public void GramoAKilogramoAsync(double gramos, bool gramosSpecified, object userState) {
            if ((this.GramoAKilogramoOperationCompleted == null)) {
                this.GramoAKilogramoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGramoAKilogramoOperationCompleted);
            }
            this.InvokeAsync("GramoAKilogramo", new object[] {
                        gramos,
                        gramosSpecified}, this.GramoAKilogramoOperationCompleted, userState);
        }
        
        private void OnGramoAKilogramoOperationCompleted(object arg) {
            if ((this.GramoAKilogramoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GramoAKilogramoCompleted(this, new GramoAKilogramoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IConversorUnidadesWS/KilogramoALibra", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void KilogramoALibra(double kilogramos, [System.Xml.Serialization.XmlIgnoreAttribute()] bool kilogramosSpecified, out double KilogramoALibraResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool KilogramoALibraResultSpecified) {
            object[] results = this.Invoke("KilogramoALibra", new object[] {
                        kilogramos,
                        kilogramosSpecified});
            KilogramoALibraResult = ((double)(results[0]));
            KilogramoALibraResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void KilogramoALibraAsync(double kilogramos, bool kilogramosSpecified) {
            this.KilogramoALibraAsync(kilogramos, kilogramosSpecified, null);
        }
        
        /// <remarks/>
        public void KilogramoALibraAsync(double kilogramos, bool kilogramosSpecified, object userState) {
            if ((this.KilogramoALibraOperationCompleted == null)) {
                this.KilogramoALibraOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKilogramoALibraOperationCompleted);
            }
            this.InvokeAsync("KilogramoALibra", new object[] {
                        kilogramos,
                        kilogramosSpecified}, this.KilogramoALibraOperationCompleted, userState);
        }
        
        private void OnKilogramoALibraOperationCompleted(object arg) {
            if ((this.KilogramoALibraCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KilogramoALibraCompleted(this, new KilogramoALibraCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IConversorUnidadesWS/LibraAKilogramo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void LibraAKilogramo(double libras, [System.Xml.Serialization.XmlIgnoreAttribute()] bool librasSpecified, out double LibraAKilogramoResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool LibraAKilogramoResultSpecified) {
            object[] results = this.Invoke("LibraAKilogramo", new object[] {
                        libras,
                        librasSpecified});
            LibraAKilogramoResult = ((double)(results[0]));
            LibraAKilogramoResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void LibraAKilogramoAsync(double libras, bool librasSpecified) {
            this.LibraAKilogramoAsync(libras, librasSpecified, null);
        }
        
        /// <remarks/>
        public void LibraAKilogramoAsync(double libras, bool librasSpecified, object userState) {
            if ((this.LibraAKilogramoOperationCompleted == null)) {
                this.LibraAKilogramoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLibraAKilogramoOperationCompleted);
            }
            this.InvokeAsync("LibraAKilogramo", new object[] {
                        libras,
                        librasSpecified}, this.LibraAKilogramoOperationCompleted, userState);
        }
        
        private void OnLibraAKilogramoOperationCompleted(object arg) {
            if ((this.LibraAKilogramoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LibraAKilogramoCompleted(this, new LibraAKilogramoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IConversorUnidadesWS/GramoALibra", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GramoALibra(double gramos, [System.Xml.Serialization.XmlIgnoreAttribute()] bool gramosSpecified, out double GramoALibraResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool GramoALibraResultSpecified) {
            object[] results = this.Invoke("GramoALibra", new object[] {
                        gramos,
                        gramosSpecified});
            GramoALibraResult = ((double)(results[0]));
            GramoALibraResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void GramoALibraAsync(double gramos, bool gramosSpecified) {
            this.GramoALibraAsync(gramos, gramosSpecified, null);
        }
        
        /// <remarks/>
        public void GramoALibraAsync(double gramos, bool gramosSpecified, object userState) {
            if ((this.GramoALibraOperationCompleted == null)) {
                this.GramoALibraOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGramoALibraOperationCompleted);
            }
            this.InvokeAsync("GramoALibra", new object[] {
                        gramos,
                        gramosSpecified}, this.GramoALibraOperationCompleted, userState);
        }
        
        private void OnGramoALibraOperationCompleted(object arg) {
            if ((this.GramoALibraCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GramoALibraCompleted(this, new GramoALibraCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IConversorUnidadesWS/LibraAGramo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void LibraAGramo(double libras, [System.Xml.Serialization.XmlIgnoreAttribute()] bool librasSpecified, out double LibraAGramoResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool LibraAGramoResultSpecified) {
            object[] results = this.Invoke("LibraAGramo", new object[] {
                        libras,
                        librasSpecified});
            LibraAGramoResult = ((double)(results[0]));
            LibraAGramoResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void LibraAGramoAsync(double libras, bool librasSpecified) {
            this.LibraAGramoAsync(libras, librasSpecified, null);
        }
        
        /// <remarks/>
        public void LibraAGramoAsync(double libras, bool librasSpecified, object userState) {
            if ((this.LibraAGramoOperationCompleted == null)) {
                this.LibraAGramoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLibraAGramoOperationCompleted);
            }
            this.InvokeAsync("LibraAGramo", new object[] {
                        libras,
                        librasSpecified}, this.LibraAGramoOperationCompleted, userState);
        }
        
        private void OnLibraAGramoOperationCompleted(object arg) {
            if ((this.LibraAGramoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LibraAGramoCompleted(this, new LibraAGramoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/ConUni_Soap_Dotnet_GR06.Modelos")]
    public partial class RespuestaAutenticacion {
        
        private bool exitosoField;
        
        private bool exitosoFieldSpecified;
        
        private string mensajeField;
        
        private string usernameField;
        
        /// <remarks/>
        public bool Exitoso {
            get {
                return this.exitosoField;
            }
            set {
                this.exitosoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExitosoSpecified {
            get {
                return this.exitosoFieldSpecified;
            }
            set {
                this.exitosoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RespuestaAutenticacion Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RespuestaAutenticacion)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void CelsiusAFahrenheitCompletedEventHandler(object sender, CelsiusAFahrenheitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CelsiusAFahrenheitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CelsiusAFahrenheitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double CelsiusAFahrenheitResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool CelsiusAFahrenheitResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void FahrenheitACelsiusCompletedEventHandler(object sender, FahrenheitACelsiusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FahrenheitACelsiusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FahrenheitACelsiusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double FahrenheitACelsiusResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool FahrenheitACelsiusResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void CelsiusAKelvinCompletedEventHandler(object sender, CelsiusAKelvinCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CelsiusAKelvinCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CelsiusAKelvinCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double CelsiusAKelvinResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool CelsiusAKelvinResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void KelvinACelsiusCompletedEventHandler(object sender, KelvinACelsiusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KelvinACelsiusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KelvinACelsiusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double KelvinACelsiusResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool KelvinACelsiusResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void FahrenheitAKelvinCompletedEventHandler(object sender, FahrenheitAKelvinCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FahrenheitAKelvinCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FahrenheitAKelvinCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double FahrenheitAKelvinResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool FahrenheitAKelvinResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void KelvinAFahrenheitCompletedEventHandler(object sender, KelvinAFahrenheitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KelvinAFahrenheitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KelvinAFahrenheitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double KelvinAFahrenheitResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool KelvinAFahrenheitResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void MetroAKilometroCompletedEventHandler(object sender, MetroAKilometroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MetroAKilometroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MetroAKilometroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double MetroAKilometroResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool MetroAKilometroResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void KilometroAMetroCompletedEventHandler(object sender, KilometroAMetroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KilometroAMetroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KilometroAMetroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double KilometroAMetroResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool KilometroAMetroResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void MetroAMillaCompletedEventHandler(object sender, MetroAMillaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MetroAMillaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MetroAMillaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double MetroAMillaResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool MetroAMillaResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void MillaAMetroCompletedEventHandler(object sender, MillaAMetroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MillaAMetroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MillaAMetroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double MillaAMetroResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool MillaAMetroResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void KilometroAMillaCompletedEventHandler(object sender, KilometroAMillaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KilometroAMillaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KilometroAMillaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double KilometroAMillaResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool KilometroAMillaResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void MillaAKilometroCompletedEventHandler(object sender, MillaAKilometroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MillaAKilometroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MillaAKilometroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double MillaAKilometroResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool MillaAKilometroResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void KilogramoAGramoCompletedEventHandler(object sender, KilogramoAGramoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KilogramoAGramoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KilogramoAGramoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double KilogramoAGramoResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool KilogramoAGramoResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void GramoAKilogramoCompletedEventHandler(object sender, GramoAKilogramoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GramoAKilogramoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GramoAKilogramoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double GramoAKilogramoResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool GramoAKilogramoResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void KilogramoALibraCompletedEventHandler(object sender, KilogramoALibraCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KilogramoALibraCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KilogramoALibraCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double KilogramoALibraResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool KilogramoALibraResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void LibraAKilogramoCompletedEventHandler(object sender, LibraAKilogramoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LibraAKilogramoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LibraAKilogramoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double LibraAKilogramoResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool LibraAKilogramoResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void GramoALibraCompletedEventHandler(object sender, GramoALibraCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GramoALibraCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GramoALibraCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double GramoALibraResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool GramoALibraResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void LibraAGramoCompletedEventHandler(object sender, LibraAGramoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LibraAGramoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LibraAGramoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double LibraAGramoResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool LibraAGramoResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591